package no.brathen.esptemp.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import no.brathen.esptemp.R

/**
 * Runs the Credential Manager Google sign-in flow and returns the Google ID token
 * to hand to Firebase (GoogleAuthProvider). The server client id comes from
 * R.string.default_web_client_id, generated by the google-services plugin from
 * google-services.json (the web/client_type=3 OAuth client).
 */
suspend fun getGoogleIdToken(context: Context): String {
    val option = GetGoogleIdOption.Builder()
        .setServerClientId(context.getString(R.string.default_web_client_id))
        .setFilterByAuthorizedAccounts(false)
        .build()
    val request = GetCredentialRequest.Builder().addCredentialOption(option).build()

    val response = CredentialManager.create(context).getCredential(context, request)
    val credential = response.credential
    if (credential is CustomCredential &&
        credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
    ) {
        return GoogleIdTokenCredential.createFrom(credential.data).idToken
    }
    throw IllegalStateException("Uventet legitimasjonstype fra Credential Manager.")
}
